name: Sync from GitLab to GitHub

on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://gitlab.com/simonpunk/susfs4ksu.git || true
          git fetch upstream

      - name: Sync all branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          branches=(
            master
            gki-android12-5.10
            gki-android13-5.10
            gki-android13-5.15
            gki-android14-5.15
            gki-android14-6.1
            gki-android15-6.6
            kernel-4.14
            kernel-4.19
            kernel-4.9
            kernel-5.4
          )
          for branch in "${branches[@]}"; do
            echo "Syncing branch: $branch"
            git checkout -B "$branch" "upstream/$branch"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} "$branch" --force
          done
